# Generated by Django 6.0.1 on 2026-01-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="sum_payment",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="Сумма платежа"
            ),
        ),
    ]
