# Generated by Django 6.0.1 on 2026-01-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_sum_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_payment",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата платежа"),
        ),
    ]
