# Generated by Django 6.0.1 on 2026-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_date_payment_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите cсылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Cсылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите Id сессии",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
    ]
