# Generated by Django 6.0.1 on 2026-02-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите cсылку на оплату",
                null=True,
                verbose_name="Cсылка на оплату",
            ),
        ),
    ]
