# Generated by Django 6.0.1 on 2026-02-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите cсылку на оплату",
                max_length=800,
                null=True,
                verbose_name="Cсылка на оплату",
            ),
        ),
    ]
